# sh2h u7e2 = Zoxa CI/CD
n: u7e2
on:
  push: {br: [main, dev]}
  pull_request: {br: [main]}
j:
  qH:
    r: ubuntu-latest
    s:
      - u: actions/checkout@v4
      - n: pn
        u: pnpm/action-setup@v4
        w:
          v: 10
      - n: nd
        u: actions/setup-node@v4
        w:
          nv: 22
          c: pnpm
      - n: d
        r: pnpm i --frozen-lockfile
      - n: l
        r: pnpm lint
      - n: b
        r: pnpm build
      - n: t
        r: pnpm test -- --passWithNoTests
  d:
    n: d
    r: ubuntu-latest
    if: gH.REF == 'refs/heads/main'
    nd: [qH]
    s:
      - u: actions/checkout@v4
      - n: pn
        u: pnpm/action-setup@v4
        w:
          v: 10
      - n: nd
        u: actions/setup-node@v4
        w:
          nv: 22
          c: pnpm
      - n: d
        r: pnpm i --frozen-lockfile
      - n: b
        r: pnpm build
      - n: vc
        u: amondnet/vercel-action@v25
        w:
          vt: \${{ s.VT }}
          o: fx-f
          i: 25
          p: zoxa-v2
          d: main
          sp: main